# INDEX 
  
 

In [2]:
num = [10,12,14,16,18,20]
num.index(12)

1

In [3]:
import numpy
numpy.array([1,2,4])


array([1, 2, 4])

In [5]:
list1 = [1,2,3,4,5,6,7]
sq = [i**2 for i in list1]
print(sq)

[1, 4, 9, 16, 25, 36, 49]


In [6]:
print(list1)

[1, 2, 3, 4, 5, 6, 7]


In [8]:
n1 = numpy.array(list1)

In [9]:
print(n1)

[1 2 3 4 5 6 7]


In [19]:
import numpy as ns
import time

list1 = [i**2 for i in range(1,100000)]
list2 = [i**3 for i in range(1,100000)]

start_time = time.time()
k = list(map(lambda x,y:x*y,list1,list2))
end_time=time.time()
exe_time=end_time-start_time
print(exe_time,"using list concept")

0.015040159225463867 using list concept


In [20]:
np1=numpy.array(list1)
np2=numpy.array(list2)
start=time.time()
prod=np1*np2
stop=time.time()
exe=stop-start
print(exe,"using numpy")

0.0 using numpy


# arrange

In [21]:
import numpy as np

In [23]:
np.arange(1,30)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [28]:
for i in range(1,30):
    print(i,end='  ')

1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27  28  29  

In [30]:
ns.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [32]:
k = ns.array(ns.arange(1,10))

In [33]:
print(k)

[1 2 3 4 5 6 7 8 9]


### 2d array

In [50]:
num = ns.array([[0,3,5],[2,4,9],[6,7,8]])
print(num)

[[0 3 5]
 [2 4 9]
 [6 7 8]]


In [51]:
num.ndim

2

In [52]:
num[1,2]

9

In [53]:
num[2,:]

array([6, 7, 8])

In [54]:
num[:,2]

array([5, 9, 8])

## 3d array

In [56]:
mn = np.array(np.arange(1,25).reshape(2,3,4))

In [57]:
mn

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [59]:
ns.ones([5,5],dtype = 'str')

array([['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1']], dtype='<U1')

eye----elegant yellow elephant

In [61]:
ns.eye(5,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [62]:
num

array([[0, 3, 5],
       [2, 4, 9],
       [6, 7, 8]])

In [64]:
ns.linalg.det(num)

64.00000000000003

In [65]:
ns.linalg.inv(num)

array([[-0.484375,  0.171875,  0.109375],
       [ 0.59375 , -0.46875 ,  0.15625 ],
       [-0.15625 ,  0.28125 , -0.09375 ]])

In [66]:
num.T

array([[0, 2, 6],
       [3, 4, 7],
       [5, 9, 8]])

In [67]:
ns.linalg.eig(num)

(array([16.34005586, -3.06012116, -1.27993471]),
 array([[-0.33333333, -0.33333333,  0.33333333],
        [-0.59022927, -0.70441005, -0.84365893],
        [-0.7351995 ,  0.62665411,  0.42086638]]))

In [68]:
ns.sin(45)

0.8509035245341184

In [72]:
ns.exp(1)

2.718281828459045

In [70]:
ns.log(89)

4.48863636973214