In [6]:

def prime(n):
    c=0
    for i in range(1,n+1):
        if(n%1==0):
            c=c+1
    if (c==2):
        print('is prime')
    else:
        print('is not prime')
prime(8)

is not prime


In [26]:
def fac_count(a):
    c=0
    for i in range(1,a+1):
        if a%i == 0:
            c = c+1
    return c
f = fac_count(9)
print(f)

3


In [27]:
def isprime(a):
    fc = fac_count(a)
    if fc == 2:
        return True
    return False
isprime(8)

False

In [28]:
i = int(input())
if isprime(i):
    print("is prime")
else:
    print("is not prime")
    

2
is prime


In [38]:
lb= int(input())
ub=int(input())
prim_range(lb,ub)
def prim_range(lb,ub):
    for i in range(lb,ub+1):
        if isprime(i):
            print(i,end = ' ')

1
1000
2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97 101 103 107 109 113 127 131 137 139 149 151 157 163 167 173 179 181 191 193 197 199 211 223 227 229 233 239 241 251 257 263 269 271 277 281 283 293 307 311 313 317 331 337 347 349 353 359 367 373 379 383 389 397 401 409 419 421 431 433 439 443 449 457 461 463 467 479 487 491 499 503 509 521 523 541 547 557 563 569 571 577 587 593 599 601 607 613 617 619 631 641 643 647 653 659 661 673 677 683 691 701 709 719 727 733 739 743 751 757 761 769 773 787 797 809 811 821 823 827 829 839 853 857 859 863 877 881 883 887 907 911 919 929 937 941 947 953 967 971 977 983 991 997 

In [92]:
def primes(n):
    if n<2:
        return False
    for i in range(2,n//2+1):
        if n%i==0:
            return False
    return True
primes(6)


False

# maps

In [47]:
l = list(map(int,['1','2','3']))
print(l)

[1, 2, 3]


In [50]:
list(map(int,l))

[1, 2, 3]

In [51]:
list(map(str,l))

['1', '2', '3']

In [53]:
i = input().split()


python sai


In [58]:
list(map(str,input().split()))

kjdfgh


['kjdfgh']

In [60]:
list(map(str,input()))

adhfg


['a', 'd', 'h', 'f', 'g']

In [61]:
def addition(n):
    return n+n

In [62]:
list(map(addition,[3,5,7,8,9,423]))

[6, 10, 14, 16, 18, 846]

In [63]:
def power(n):
    return n**n

In [65]:
list(map(power,[3,6,7,2]))

[27, 46656, 823543, 4]

In [70]:
def square(n):
    return n*n
l = list(map(square,[3,54,45,435,4]))
for i in l:
    print(i)

9
2916
2025
189225
16


## Filters in Python

In [77]:
Li = [1,2,'a','b','c',3]
def isDigit(n):
    n = str(n)
    if n.isdigit():
        return True
    return False

list(filter(isDigit,Li))

[1, 2, 3]

In [93]:
Li = [1,2,7,9,3,4,3]
def isDigit(n):
    n = str(n)
    if n.isdigit():
        return True
    return False

list(filter(isDigit,Li))
list(filter(primes,Li))

[2, 7, 3, 3]

In [94]:
def even(n):
    if n%2==0:
        return True
list(filter(even,Li))

[2, 4]

In [95]:
def odd(n):
    if n%2!=0:
        return True
list(filter(odd,Li))

[1, 7, 9, 3, 3]

# LAMBDAS

In [1]:
h = lambda x : x%2==0
list(filter(h,[1,2,3,4,5]))

[2, 4]

In [4]:
def odd_fun(n):
    if n%2!=0:
        return True
    return False

In [5]:
l = [1,2,3,4,5,6,7,8,9,10]
o = lambda i:i%2!=0
list(filter(o,l))

[1, 3, 5, 7, 9]

In [7]:
from random  import randint as r
for i in range(1,10+1):
    print(r(1,25))

9
14
20
6
2
19
8
8
2
24


In [8]:
print([r(1,25) for i in range(1,11)])

[22, 25, 7, 11, 5, 9, 16, 21, 6, 10]


In [10]:
m1 = [r(1,25) for i in range(1,11)]
m2 = [r(1,25) for i in range(1,11)]
m3 = [r(1,25) for i in range(1,11)]
print(m1)
print(m2)
print(m3)

[22, 12, 23, 24, 21, 11, 4, 13, 11, 14]
[20, 24, 2, 11, 15, 1, 10, 17, 20, 22]
[21, 24, 14, 21, 3, 8, 14, 9, 18, 16]


In [33]:
a1 = list(map(lambda x,y:(x+y)//2,m1,m2))
print(a1)

[21, 18, 12, 17, 18, 6, 7, 15, 15, 18]


In [29]:
a2 = list(map(lambda x,y,z:(x+y+z)//3,m1,m2,m3))
print(a2)

[21, 20, 13, 18, 13, 6, 9, 13, 16, 17]


In [16]:
3+5+5


13

In [17]:
                13/3

4.333333333333333

In [34]:
k = lambda x:x<10
list(filter(k,a1))

[6, 7]

In [27]:
r = lambda x:x<10
list(filter(r,a2))

[6, 9]

In [31]:
a2
S

[21, 20, 13, 18, 13, 6, 9, 13, 16, 17]

## Numpy

In [35]:
import numpy as np


In [36]:
l = [1,2,3,4]
a1 = np.array(l)
print(a1)

[1 2 3 4]


In [37]:
l2 = [[1,2,3],[4,5,6]]
a2 = np.array(l2)
print(a2)

[[1 2 3]
 [4 5 6]]


In [39]:
l3 = [[1,2,3],[4,5,6],[6,7,8]]
a3 = np.array(l3)
print(a3)

[[1 2 3]
 [4 5 6]
 [6 7 8]]


In [44]:
a = np.arange(100).reshape(5,20)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [46]:
b = np.arange(20,30).reshape(2,5)
print(b)

[[20 21 22 23 24]
 [25 26 27 28 29]]


In [48]:
c = np.arange(20,26).reshape(2,3)
print(c)

[[20 21 22]
 [23 24 25]]


In [61]:

x = np.arange(1,7).reshape(2,3)
y = np.arange(22,28).reshape(2,3)
z= np.arange(11,17).reshape(2,3)
x
y
z

array([[11, 12, 13],
       [14, 15, 16]])